site_name: affectedpkgs
site_description: A CLI tool to find packages affected by a specific dependency in Go modules.
site_url: https://sebakri.github.io/affectedpkgs/

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md

theme:
  name: simple-blog

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "#"